version: '3.8'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/app

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
